# Generated by Django 5.2.1 on 2025-06-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_short_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
