# Generated by Django 5.2.11 on 2026-02-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_activity_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='outstanding',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
