# Generated by Django 5.2.11 on 2026-02-09 13:52

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_activityregistration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Jarduera', 'verbose_name_plural': 'Jarduerak'},
        ),
        migrations.AlterModelOptions(
            name='activityregistration',
            options={'verbose_name': 'Jardueraren izen-ematea', 'verbose_name_plural': 'Jardueretako izen-emateak'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activityDateHour',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data eta ordua'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Egilea'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Edukia'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='outstanding',
            field=models.BooleanField(blank=True, null=True, verbose_name='Nabarmendua'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Prezioa'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='published',
            field=models.BooleanField(blank=True, null=True, verbose_name='Argitaratua'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short',
            field=models.TextField(blank=True, null=True, verbose_name='Laburpena'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Izenburua'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='activity.activity', verbose_name='Jarduera'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='anonymous',
            field=models.BooleanField(default=False, verbose_name='Erregistro anonimoa'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='federation_member',
            field=models.BooleanField(default=False, verbose_name='Mendi federazioko kidea'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='locality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Herria'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Izena'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Abizena'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erabiltzailea'),
        ),
    ]
