# Generated by Django 5.2.11 on 2026-02-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-published_at'], 'verbose_name': 'Jarduera', 'verbose_name_plural': 'Jarduerak'},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activityDateHour',
            new_name='activity_date_time',
        ),
        migrations.AddField(
            model_name='activity',
            name='show_price',
            field=models.BooleanField(default=True, verbose_name='Show price'),
        ),
        migrations.AddField(
            model_name='activity',
            name='show_registration_button',
            field=models.BooleanField(default=True, verbose_name='Show registration button'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activity/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='outstanding',
            field=models.BooleanField(default=False, verbose_name='Nabarmendua'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Prezioa'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Argitaratua'),
        ),
    ]
