# Generated by Django 5.2.11 on 2026-02-15 19:09

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Informazio osoa'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='short',
            field=models.TextField(blank=True, null=True, verbose_name='Informazio laburra'),
        ),
    ]
