# Generated by Django 5.2.11 on 2026-02-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_remove_activity_image_activity_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='audience',
            field=models.CharField(choices=[('anyone', 'Cualquier persona'), ('members', 'Solo socios'), ('children', 'Niños'), ('adults', 'Adultos'), ('families', 'Familias'), ('members_children', 'Socios y niños')], default='anyone', max_length=30, verbose_name='Público'),
        ),
        migrations.AddField(
            model_name='activity',
            name='audience_note',
            field=models.CharField(blank=True, help_text='Ej: “Menores acompañados”, “A partir de 12 años”…', max_length=160, null=True, verbose_name='Nota adicional'),
        ),
    ]
