# Generated by Django 5.2.11 on 2026-02-23 17:14

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0011_activity_audience_activity_audience_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='audience',
            field=models.CharField(choices=[('anyone', 'Edozein pertsona'), ('members', 'Bazkideak'), ('children', 'Haurrak'), ('adults', 'Helduak'), ('families', 'Familiak'), ('members_children', 'Bazkideak eta haurrak')], default='anyone', max_length=30, verbose_name='Nork hartu dezake parte?'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='audience_note',
            field=models.CharField(blank=True, help_text='Ej: “Haurrak heldu batekin lagundua”, “12 urtetik aurrera”…', max_length=160, null=True, verbose_name='Ohar gehigarria'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Antolatzailea'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Informazio osoa xehetasun guztiekin'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='show_price',
            field=models.BooleanField(default=True, verbose_name='Prezioa agertzea'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='show_registration_button',
            field=models.BooleanField(default=True, verbose_name='Izena emateko botoia agertzea'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL testua (tartetik ez utzi)'),
        ),
    ]
