# Generated by Django 5.2.11 on 2026-02-23 17:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_alter_activity_audience_alter_activity_audience_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-published_at', '-created_at'], 'permissions': [('can_publish_activity', 'Can publish activities'), ('can_review_activity', 'Can review/validate activities')], 'verbose_name': 'Jarduera', 'verbose_name_plural': 'Jarduerak'},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='published',
        ),
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Sortze-data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Sortzailea'),
        ),
        migrations.AddField(
            model_name='activity',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_activities', to=settings.AUTH_USER_MODEL, verbose_name='Nork argitaratu du'),
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('draft', 'Zirriborroa'), ('pending', 'Balidazio zain'), ('published', 'Argitaratua'), ('archived', 'Artxibatua')], db_index=True, default='draft', max_length=12, verbose_name='Egoera'),
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Eguneratua'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Argitaratze-data'),
        ),
    ]