# Generated by Django 5.2.11 on 2026-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_alter_activity_options_remove_activity_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='audience',
            field=models.CharField(choices=[('Edozein pertsona', 'Edozein pertsona'), ('Bazkideak', 'Bazkideak'), ('Haurrak', 'Haurrak'), ('Helduak', 'Helduak'), ('Familiak', 'Familiak'), ('Bazkideak eta haurrak', 'Bazkideak eta haurrak')], default='Edozein pertsona', max_length=30, verbose_name='Nork hartu dezake parte?'),
        ),
    ]
