# Generated by Django 5.2.11 on 2026-03-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_alter_activity_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='audience',
            field=models.CharField(choices=[('Edozein pertsonak', 'Edozein pertsona'), ('Bazkideek', 'Bazkideak'), ('Haurrak', 'Haurrak'), ('Helduak', 'Helduak'), ('Familiak', 'Familiak'), ('Bazkideak eta haurrak', 'Bazkideak eta haurrak')], default='Edozein pertsonak', max_length=30, verbose_name='Nork hartu dezake parte?'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='anonymous',
            field=models.CharField(choices=[('yes', 'Bai'), ('no', 'Ez')], default='no', max_length=3, verbose_name='Erregistro anonimoa'),
        ),
        migrations.AlterField(
            model_name='activityregistration',
            name='federation_member',
            field=models.CharField(choices=[('yes', 'Bai'), ('no', 'Ez')], max_length=3, verbose_name='Mendi federazioko kidea'),
        ),
    ]
