# Generated by Django 5.2.11 on 2026-03-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_alter_activity_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='audience',
            field=models.CharField(choices=[('Edozein pertsonak', 'Edozein pertsonak'), ('Bazkideek', 'Bazkideak'), ('Haurrak', 'Haurrak'), ('Helduak', 'Helduak'), ('Familiak', 'Familiak'), ('Bazkideak eta haurrak', 'Bazkideak eta haurrak')], default='Edozein pertsonak', max_length=30, verbose_name='Nork hartu dezake parte?'),
        ),
    ]
