# Generated by Django 5.2.12 on 2026-03-16 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0016_alter_activity_audience'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Galdera')),
                ('answer', models.TextField(verbose_name='Erantzuna')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordena')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_answers', to='activity.activity', verbose_name='Jarduera')),
            ],
            options={
                'verbose_name': 'Jardueraren galdera/erantzuna',
                'verbose_name_plural': 'Jardueraren galderak eta erantzunak',
                'ordering': ['order', 'id'],
            },
        ),
    ]
