# Generated by Django 5.2.13 on 2026-04-16 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0017_activityquestionanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='currency',
            field=models.CharField(default='eur', help_text='Stripe-rako ISO moneta-kodea. Adibidez: eur', max_length=3, verbose_name='Moneta'),
        ),
        migrations.AddField(
            model_name='activity',
            name='requires_payment',
            field=models.BooleanField(default=False, verbose_name='Ordainketa behar du'),
        ),
        migrations.CreateModel(
            name='ActivityRegistrationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Stripe Checkout Session ID')),
                ('status', models.CharField(choices=[('pending', 'Ordainketa zain'), ('completed', 'Ordainduta'), ('canceled', 'Bertan behera')], db_index=True, default='pending', max_length=12, verbose_name='Egoera')),
                ('registration_data', models.JSONField(verbose_name='Izen-emate datuak')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Zenbatekoa')),
                ('currency', models.CharField(default='eur', max_length=3, verbose_name='Moneta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_payments', to='activity.activity', verbose_name='Jarduera')),
                ('registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='activity.activityregistration', verbose_name='Izen-ematea')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Erabiltzailea')),
            ],
            options={
                'verbose_name': 'Jarduera izen-ematearen ordainketa',
                'verbose_name_plural': 'Jarduera izen-emateen ordainketak',
                'ordering': ['-created_at'],
            },
        ),
    ]
