# Generated by Django 5.2.13 on 2026-04-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_activity_currency_activity_requires_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityregistration',
            name='confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Baieztapen emaila bidalita'),
        ),
    ]
