# Generated by Django 5.2.13 on 2026-04-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0019_activityregistration_confirmation_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityregistrationpayment',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('on_event', 'Ekitaldiaren egunean')], default='stripe', max_length=12, verbose_name='Ordainketa modua'),
        ),
    ]
