services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "1"