services:
  web:
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --access-logfile - --error-logfile - --log-level debug
    ports:
      - "127.0.0.1:8010:8000"
    restart: always
    environment:
      DJANGO_DEBUG: "0"
    volumes:
      - ./src/staticfiles:/app/staticfiles
      - ./src/media:/app/media