# Generated by Django 5.2.1 on 2025-06-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='history/'),
        ),
    ]
