# Generated by Django 5.2.11 on 2026-02-09 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_alter_profile_address_alter_profile_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Bazkidea', 'verbose_name_plural': 'Bazkideak'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Helbidea'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Jaiotze-data'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='movil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono mugikorra'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='movil2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bigarren mugikorra'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='partner_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bazkide-data'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='partner_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Bazkide zenbakia'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='related_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_profiles', to='partner.profile', verbose_name='Lotutako bazkidea'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erabiltzailea'),
        ),
    ]
