# Generated by Django 5.2.1 on 2025-06-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gallery_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='titulo',
            new_name='title',
        ),
    ]
