# Generated by Django 5.2.1 on 2025-06-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_contenido_gallery_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='autor',
            new_name='author',
        ),
    ]
