# Generated by Django 5.2.1 on 2025-06-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_fecha_creacion_gallery_published_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='imagen',
            new_name='image',
        ),
    ]
