# Generated by Django 5.2.11 on 2026-02-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Izenburua')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='Edukia')),
                ('short_text', models.CharField(blank=True, help_text='If empty, title will be shown in banner.', max_length=255, verbose_name='Testu laburra (bannerrean)')),
                ('visibility', models.CharField(choices=[('public', 'Publikoa'), ('members', 'Bazkideentzat bakarrik'), ('board', 'Zuzendaritzarentzat bakarrik')], default='members', max_length=20, verbose_name='Ikusgarritasuna')),
                ('start_date', models.DateTimeField(verbose_name='Hasiera data')),
                ('end_date', models.DateTimeField(verbose_name='Amaiera data')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiboa')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = shown first', verbose_name='Lehentasuna')),
                ('banner_style', models.CharField(choices=[('info', 'Info (blue)'), ('warning', 'Warning (yellow)'), ('danger', 'Danger (red)'), ('success', 'Success (green)')], default='warning', max_length=20, verbose_name='Banner estiloa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Komunikatua',
                'verbose_name_plural': 'Komunikatuak',
                'ordering': ['-priority', '-start_date'],
            },
        ),
    ]
