# Generated by Django 5.2.11 on 2026-02-09 13:52

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Albistea', 'verbose_name_plural': 'Albisteak'},
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Egilea'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Edukia'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Irudia'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.BooleanField(blank=True, null=True, verbose_name='Argitaratua'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Argitaratze-data'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short',
            field=models.TextField(blank=True, null=True, verbose_name='Laburpena'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Izenburua'),
        ),
    ]
