# Generated by Django 5.2.11 on 2026-02-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_options_alter_news_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at'], 'verbose_name': 'Albistea', 'verbose_name_plural': 'Albisteak'},
        ),
        migrations.AddField(
            model_name='news',
            name='visibility',
            field=models.CharField(choices=[('public', 'Publikoa'), ('members', 'Bazkideentzat bakarrik')], default='public', max_length=20, verbose_name='Ikusgarritasuna'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Argitaratua'),
        ),
    ]
