# Generated by Django 5.2.12 on 2026-03-15 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_alter_profile_options_alter_profile_address_and_more'),
        ('tpv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='partner.profile'),
        ),
    ]
