# Generated by Django 5.2.1 on 2025-06-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_titulo_gallery_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='contenido',
            new_name='content',
        ),
    ]
