# Generated by Django 5.2.1 on 2025-06-07 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_autor_gallery_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='fecha_creacion',
            new_name='published_at',
        ),
    ]
