# Generated by Django 5.2.3 on 2025-07-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_gallery_photodate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
