# Generated by Django 5.2.11 on 2026-02-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0009_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(help_text='Nombre de la persona (ej. Director / Presidenta)', max_length=100)),
                ('cargo', models.CharField(help_text='Cargo dentro de la asociación', max_length=100)),
                ('texto_bienvenida', models.TextField(help_text='Texto de bienvenida que aparece en la home')),
                ('tarifa1', models.CharField(blank=True, help_text='Tarifa 1 (ej. Socio anual)', max_length=100)),
                ('tarifa2', models.CharField(blank=True, help_text='Tarifa 2 (ej. Socio familiar)', max_length=100)),
                ('tarifa3', models.CharField(blank=True, help_text='Tarifa 3 (ej. Evento puntual)', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido de la Home',
                'verbose_name_plural': 'Contenido de la Home',
            },
        ),
    ]
