# Generated by Django 5.2.11 on 2026-02-15 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecontent',
            old_name='nombre1',
            new_name='director_name',
        ),
    ]
