# Generated by Django 5.2.11 on 2026-02-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_nombre1_homecontent_director_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecontent',
            old_name='cargo',
            new_name='director_position',
        ),
    ]
