# Generated by Django 5.2.11 on 2026-02-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_cargo_homecontent_director_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homecontent',
            old_name='texto_bienvenida',
            new_name='director_welcome_text',
        ),
    ]
