# Generated by Django 5.2.11 on 2026-02-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_texto_bienvenida_homecontent_director_welcome_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='director_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/'),
        ),
    ]
