# Generated by Django 5.2.11 on 2026-02-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homecontent_director_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='tarifa1',
        ),
        migrations.AddField(
            model_name='homecontent',
            name='membership_fee_1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='show_director_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='show_membership_section',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='show_welcome_section',
            field=models.BooleanField(default=True),
        ),
    ]
