# Generated by Django 5.2.11 on 2026-02-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_homecontent_tarifa1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='tarifa2',
        ),
        migrations.AddField(
            model_name='homecontent',
            name='membership_fee_2',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
