# Generated by Django 5.2.11 on 2026-02-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_homecontent_tarifa3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='membership_button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='membership_button_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
