# Generated by Django 5.2.11 on 2026-02-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_homecontent_membership_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='show_membership_button',
            field=models.BooleanField(default=True),
        ),
    ]
