# Generated by Django 5.2.11 on 2026-02-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_homecontent_show_membership_button'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='membership_fee_1',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='membership_fee_2',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='membership_fee_3',
        ),
    ]
