# Generated by Django 5.2.11 on 2026-02-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_homecontent_membership_fee_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='membership_info_text',
            field=models.TextField(default=1, help_text='Texto informativa para nuevos socios'),
            preserve_default=False,
        ),
    ]
