# Generated by Django 5.2.11 on 2026-02-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_homecontent_membership_info_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='activities_per_year',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate number of activities organized per year', null=True),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='foundation_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year the association was founded', null=True),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='number_of_members',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of active members', null=True),
        ),
    ]
