# Generated by Django 5.2.11 on 2026-02-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_homecontent_activities_per_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección física de la asociación', max_length=255),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='email',
            field=models.EmailField(blank=True, help_text='Correo electrónico de contacto', max_length=254),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='phone',
            field=models.CharField(blank=True, help_text='Teléfono de contacto de la asociación', max_length=30),
        ),
    ]
