# Generated by Django 5.2.11 on 2026-02-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_homecontent_address_homecontent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='association_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
