# Generated by Django 5.2.11 on 2026-02-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_homecontent_association_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='slogan',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
