# Generated by Django 5.2.11 on 2026-02-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_homecontent_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontent',
            name='activities_per_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='director_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='director_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='director_welcome_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='foundation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='membership_info_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='number_of_members',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
