# Generated by Django 5.2.11 on 2026-02-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_homecontent_activities_per_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
