# Generated by Django 5.2.1 on 2025-06-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diningRoom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='goiko_selected',
            new_name='is_birthday',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='number_of_diners',
            new_name='num_diners',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='reservation_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='urkabe_selected',
            new_name='room_goiko',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='fire_count',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='meal_options',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='oven_count',
        ),
        migrations.AddField(
            model_name='reservation',
            name='fires',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('midday', 'Midday meal'), ('dinner', 'Dinner')], max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ovens',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_urkabe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='membership_number',
            field=models.CharField(max_length=20),
        ),
    ]
