# Generated by Django 5.2.1 on 2025-06-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diningRoom', '0002_rename_goiko_selected_reservation_is_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='activities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reservation',
            name='custom_activity',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
