# Generated by Django 5.2.1 on 2025-06-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diningRoom', '0003_reservation_activities_reservation_custom_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='meal_type',
        ),
    ]
