# Generated by Django 5.2.1 on 2025-06-09 15:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diningRoom', '0004_remove_reservation_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
