# Generated by Django 5.2.1 on 2025-06-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activityDateHour',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
