# Generated by Django 5.2.11 on 2026-02-16 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField(verbose_name='Erreserba-data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sortze-data')),
                ('membership_number', models.CharField(max_length=20, verbose_name='Bazkide zenbakia')),
                ('num_diners', models.PositiveIntegerField(verbose_name='Jankide kopurua')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Erabiltzailea')),
            ],
            options={
                'verbose_name': 'Erreserba',
                'verbose_name_plural': 'Erreserbak',
                'ordering': ['-reservation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('midday', 'Midday meal'), ('merienda', 'Merienda'), ('dinner', 'Dinner'), ('other', 'Other activity')], max_length=20, verbose_name='Denbora-tartea')),
                ('selected_tables', models.JSONField(default=list, verbose_name='Hautatutako mahaiak')),
                ('room_urkabe', models.BooleanField(default=False, verbose_name='Urkabe gela')),
                ('room_goiko', models.BooleanField(default=False, verbose_name='Goiko gela')),
                ('fires', models.PositiveIntegerField(default=0, verbose_name='Sukaldeko suak')),
                ('ovens', models.PositiveIntegerField(default=0, verbose_name='Labeak')),
                ('barbacue', models.BooleanField(default=False, verbose_name='Barbakoa')),
                ('is_birthday', models.BooleanField(default=False, verbose_name='Urtebetetze ospakizuna')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='diningRoom.reservation', verbose_name='Erreserba')),
            ],
            options={
                'verbose_name': 'Erreserba-tartea',
                'verbose_name_plural': 'Erreserba-tarteak',
                'unique_together': {('reservation', 'time_slot')},
            },
        ),
    ]
