# Generated by Django 5.2.11 on 2026-02-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diningRoom', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservationslot',
            index=models.Index(fields=['time_slot'], name='diningRoom__time_sl_9b259f_idx'),
        ),
    ]
