# Generated by Django 5.2.3 on 2025-07-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='date',
            new_name='photoDate',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='published',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='short',
        ),
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
