# Generated by Django 5.2.3 on 2025-07-06 11:17

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_rename_date_gallery_photodate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='photoDate',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='slug',
        ),
        migrations.AddField(
            model_name='gallery',
            name='published',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='short',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
