# Generated by Django 5.2.11 on 2026-02-09 13:52

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_photodate_gallery_date_remove_gallery_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galeriak'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Egilea'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Edukia'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Irudia'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='published',
            field=models.BooleanField(blank=True, null=True, verbose_name='Argitaratua'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Argitaratze-data'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='short',
            field=models.TextField(blank=True, null=True, verbose_name='Laburpena'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Izenburua'),
        ),
    ]
