# Generated by Django 5.2.11 on 2026-02-16 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_gallery_options_alter_gallery_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-published_at'], 'verbose_name': 'Galeria', 'verbose_name_plural': 'Galeriak'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Argitaratua'),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/images/', verbose_name='Irudia')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Izenburua')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordena')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.gallery')),
            ],
            options={
                'verbose_name': 'Galeriako irudia',
                'verbose_name_plural': 'Galeriako irudiak',
                'ordering': ['order'],
            },
        ),
    ]
