# Generated by Django 5.2.13 on 2026-05-03 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_gallery_options_remove_gallery_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_galleries', to='gallery.galleryimage', verbose_name='Fotografía de portada'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Destacada'),
        ),
    ]
