# Generated by Django 5.2.11 on 2026-02-09 13:52

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_history_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Historia', 'verbose_name_plural': 'Historia'},
        ),
        migrations.AlterField(
            model_name='history',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Egilea'),
        ),
        migrations.AlterField(
            model_name='history',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Edukia'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='history/', verbose_name='Irudia'),
        ),
        migrations.AlterField(
            model_name='history',
            name='published',
            field=models.BooleanField(blank=True, null=True, verbose_name='Argitaratua'),
        ),
        migrations.AlterField(
            model_name='history',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Argitaratze-data'),
        ),
        migrations.AlterField(
            model_name='history',
            name='short',
            field=models.TextField(blank=True, null=True, verbose_name='Laburpena'),
        ),
        migrations.AlterField(
            model_name='history',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='history',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Izenburua'),
        ),
    ]
